<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="FluentValidation" Version="12.0.0" />
        <PackageReference Include="FluentValidation.AspNetCore" Version="11.3.1" />
        <PackageReference Include="Microsoft.AspNetCore.Authentication" Version="2.3.0" />
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.17" />
        <PackageReference Include="Microsoft.AspNetCore.JsonPatch" Version="10.0.0-preview.5.25277.114" />
        <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="8.0.17" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.15"/>
        <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="8.12.0" />
        <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="8.0.7" />
        <PackageReference Include="Riok.Mapperly" Version="4.3.0-next.0" />
        <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2"/>
    </ItemGroup>

    <ItemGroup>
      <Content Include="..\.dockerignore">
        <Link>.dockerignore</Link>
      </Content>
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Aminities\" />
      <Folder Include="Authentication\Controllers\" />
      <Folder Include="Bookings\Controllers\" />
      <Folder Include="Bookings\Dtos\Responses\" />
      <Folder Include="Bookings\Mappers\" />
      <Folder Include="Cities\Controllers\" />
      <Folder Include="Cities\Dtos\Responses\" />
      <Folder Include="Discounts\Controllers\" />
      <Folder Include="Discounts\Dtos\Requests\" />
      <Folder Include="Discounts\Dtos\Responses\" />
      <Folder Include="Discounts\Mappers\" />
      <Folder Include="Discounts\Validators\" />
      <Folder Include="Hotels\Controllers\" />
      <Folder Include="Hotels\Dtos\Responses\" />
      <Folder Include="Owners\Controllers\" />
      <Folder Include="Owners\Dtos\Responses\" />
      <Folder Include="Reviews\Controllers\" />
      <Folder Include="Reviews\Dtos\Requests\" />
      <Folder Include="Reviews\Dtos\Responses\" />
      <Folder Include="Reviews\Mappers\" />
      <Folder Include="Reviews\Validators\" />
      <Folder Include="RoomInfos\Dtos\Responses\" />
      <Folder Include="Rooms\Dtos\Responses\" />
      <Folder Include="Users\Controllers\" />
      <Folder Include="Users\Dtos\Requests\" />
      <Folder Include="Users\Dtos\Responses\" />
      <Folder Include="Users\Mappers\" />
      <Folder Include="Users\Validators\" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\TravelAndAccommodationBookingPlatform.Domain\TravelAndAccommodationBookingPlatform.Domain.csproj" />
      <ProjectReference Include="..\TravelAndAccommodationBookingPlatform.Infrastructure\TravelAndAccommodationBookingPlatform.Infrastructure.csproj" />
    </ItemGroup>

</Project>
