<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
      <PackageReference Include="brevo_csharp" Version="1.1.1" />
      <PackageReference Include="CloudinaryDotNet" Version="1.27.5" />
      <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.17" />
      <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.5" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.5" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.5">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="Microsoft.Extensions.Configuration" Version="9.0.5" />
      <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="9.0.5" />
      <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="9.0.5" />
      <PackageReference Include="Microsoft.Extensions.Identity.Core" Version="9.0.6" />
      <PackageReference Include="Microsoft.IdentityModel.JsonWebTokens" Version="8.12.1" />
      <PackageReference Include="Polly" Version="8.6.1" />
      <PackageReference Include="QuestPDF" Version="2025.5.1" />
      <PackageReference Include="Sieve" Version="3.0.0-beta0015" />
      <PackageReference Include="Stripe.net" Version="48.2.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\TravelAndAccommodationBookingPlatform.Application\TravelAndAccommodationBookingPlatform.Application.csproj" />
      <ProjectReference Include="..\TravelAndAccommodationBookingPlatform.Domain\TravelAndAccommodationBookingPlatform.Domain.csproj" />
    </ItemGroup>

</Project>
